import {
  Home,
  CalendarClock,
  MessagesSquare,
  Bookmark,
  Plus,
  CreditCard,
  User,
  Building,
  Users,
  FileText,
  Handshake,
} from 'lucide-react';

export const NAV_ITEMS = [
  { label: 'Room Browser', href: '/dashboard', icon: Home, roles: ['student'] },
  { label: 'My Bookings', href: '/dashboard/bookings', icon: FileText, roles: ['student'] },
  { label: 'Booking Requests', href: '/owner/bookings', icon: FileText, roles: ['owner'] },
  {
    label: 'Visiting Schedule',
    href: '/dashboard/visiting-schedule',
    icon: CalendarClock,
    roles: ['student'],
  },
  { label: 'Room Sharing Network', href: '/shared-rooms', icon: Users, roles: ['student'] },
  { label: 'Visit Requests', href: '/owner/visits', icon: CalendarClock, roles: ['owner'] },
  { label: 'Negotiations', href: '/dashboard/negotiations', icon: Handshake, roles: ['student'] },
  { label: 'Negotiations', href: '/owner/negotiations', icon: Handshake, roles: ['owner'] },
  { label: 'Messages', href: '/dashboard/messages', icon: MessagesSquare },
  { label: 'Saved', href: '/dashboard/saved', icon: Bookmark, roles: ['student'] },
  { label: 'Post Property', href: '/owner/post-property', icon: Plus, roles: ['owner'] },
  { label: 'My Properties', href: '/owner/properties', icon: Building, roles: ['owner'] },
  { label: 'Payments & Revenue', href: '/owner/payments', icon: CreditCard, roles: ['owner'] },
  { label: 'Student Profile', href: '/student/profile', icon: User, roles: ['student'] },
  { label: 'Owner Profile', href: '/owner/profile', icon: Building, roles: ['owner'] },
];
